#!/usr/bin/env bash
# Generates a .trivyignore file by checking which Erlang/OTP CVEs
# are already fixed in the running OTP version.
#
# NVD data often lags behind actual OTP releases — CVEs get patched
# in newer OTP versions but NVD only lists the backport (e.g. 26.x)
# as the fix. This causes scanners to flag OTP 27/28 as vulnerable
# when it's not.
#
# This script queries GitHub security advisories for erlang/otp,
# compares patched versions against the current OTP version, and
# writes a .trivyignore for CVEs that are already fixed.
set -euo pipefail

# --- Version comparison ---

# Pads version segments for lexicographic comparison
# e.g. "28.4.1" -> "00028.00004.00001"
normalize_version() {
    local ver="$1"
    echo "$ver" | awk -F'.' '{
        for (i=1; i<=NF; i++) printf "%05d", $i
        # Pad to at least 3 segments
        for (i=NF+1; i<=3; i++) printf "%05d", 0
    }'
}

# Returns 0 if $1 >= $2 (current >= patched)
version_gte() {
    local current_norm patched_norm
    current_norm=$(normalize_version "$1")
    patched_norm=$(normalize_version "$2")
    [[ "$current_norm" > "$patched_norm" || "$current_norm" == "$patched_norm" ]]
}

# --- Detect OTP version ---

detect_otp_version() {
    if [ -n "${OTP_VERSION:-}" ]; then
        echo "$OTP_VERSION"
    elif command -v erl &>/dev/null; then
        erl -eval 'io:format("~s", [erlang:system_info(otp_release)]), halt().' -noshell 2>/dev/null
    else
        echo ""
    fi
}

# Get full version including patch (e.g. "28.4.1" not just "28")
detect_otp_full_version() {
    if [ -n "${OTP_FULL_VERSION:-}" ]; then
        echo "$OTP_FULL_VERSION"
    elif command -v erl &>/dev/null; then
        erl -eval '{ok, V} = file:read_file(filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"])), io:format("~s", [string:trim(V)]), halt().' -noshell 2>/dev/null
    else
        echo ""
    fi
}

# --- Query advisories ---

fetch_advisories() {
    if ! command -v gh &>/dev/null; then
        echo "gh CLI not found, skipping advisory check" >&2
        return 1
    fi

    gh api repos/erlang/otp/security-advisories --paginate \
        --jq '.[] | {cve: .cve_id, severity: .severity, summary: .summary, patched: [.vulnerabilities[].patched_versions]}' 2>/dev/null
}

# Extract OTP-level patched version from advisory patched field
# Advisories list multiple products (OTP + individual apps)
# We want the OTP version (major >= 17)
extract_otp_patched_version() {
    local patched_json="$1" current_major="$2"
    echo "$patched_json" | jq -r '.patched[]' 2>/dev/null | while IFS= read -r versions; do
        # Split comma-separated versions
        echo "$versions" | tr ',' '\n' | while IFS= read -r v; do
            v=$(echo "$v" | xargs) # trim whitespace
            [ -z "$v" ] && continue
            local major
            major=$(echo "$v" | cut -d. -f1)
            # Match current major version
            if [ "$major" = "$current_major" ]; then
                echo "$v"
                return
            fi
        done
    done | head -1
}

# --- Main ---

generate_trivyignore() {
    local otp_version
    otp_version=$(detect_otp_full_version)

    if [ -z "$otp_version" ]; then
        echo "Could not detect OTP version, skipping .trivyignore generation" >&2
        return 0
    fi

    local otp_major
    otp_major=$(echo "$otp_version" | cut -d. -f1)

    echo "Detected OTP version: $otp_version (major: $otp_major)" >&2

    local advisories
    advisories=$(fetch_advisories) || return 0

    local ignored_cves=()
    local ignore_reasons=()

    while IFS= read -r advisory; do
        [ -z "$advisory" ] && continue
        local cve summary
        cve=$(echo "$advisory" | jq -r '.cve')
        summary=$(echo "$advisory" | jq -r '.summary')

        local patched_version
        patched_version=$(extract_otp_patched_version "$advisory" "$otp_major")

        if [ -z "$patched_version" ]; then
            continue
        fi

        if version_gte "$otp_version" "$patched_version"; then
            ignored_cves+=("$cve")
            ignore_reasons+=("$cve # Fixed in $patched_version, running $otp_version — $summary")
            echo "  Ignoring $cve: fixed in $patched_version (running $otp_version)" >&2
        fi
    done <<< "$advisories"

    if [ ${#ignored_cves[@]} -eq 0 ]; then
        echo "No CVEs to ignore — all advisories apply to OTP $otp_version" >&2
        return 0
    fi

    # Write .trivyignore
    local output="${TRIVYIGNORE_PATH:-.trivyignore}"
    local header="# Auto-generated by erlang-ci — do not edit manually
# These CVEs are already fixed in OTP $otp_version but NVD data
# has not been updated to reflect this. See:
# https://github.com/erlang/otp/security/advisories
#
# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"

    {
        echo "$header"
        echo ""
        for reason in "${ignore_reasons[@]}"; do
            echo "$reason"
        done
    } > "$output"

    echo "Wrote ${#ignored_cves[@]} ignored CVEs to $output" >&2
    echo "$output"
}

# When sourced, export functions only. When run directly or piped, generate the file.
if [ -z "${BASH_SOURCE[0]:-}" ] || [ "${BASH_SOURCE[0]}" = "$0" ]; then
    generate_trivyignore
fi
